name: Build Android App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the code from your repository
    - name: Checkout code
      uses: actions/checkout@v4  # Updated from v3 to v4

    # Step 2: Set up the Java environment (required for Android)
    - name: Set up JDK 17
      uses: actions/setup-java@v4 # Updated from v3 to v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Step 3: Set up Gradle (the build tool)
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v3 # Updated from v2 to v3

    # Step 4: Give the build script permission to run
    # This is a standard step for this environment
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    # Step 5: Build the app and create the APK file
    - name: Build with Gradle
      run: ./gradlew app:assembleDebug

    # Step 6: Upload the finished APK so you can download it
    # THIS IS THE LINE THAT CAUSED THE ERROR
    - name: Upload APK
      uses: actions/upload-artifact@v4 # <-- THE MOST IMPORTANT FIX: Updated from v3 to v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
